#!/usr/bin/env python

#create data used in tests using https://pynrrd.readthedocs.io/en/stable/

import nrrd
import numpy as np

def create_header_test():
    with open('test-headers.nrrd', 'w') as fd:
        fd.write('''\
NRRD0005
# This NRRD file was generated by hand
# Complete NRRD file format specification at:
# http://teem.sourceforge.net/nrrd/format.html
type: double
encoding: ASCII
dimension: 1
sizes: 5

0 1 3 4 5
''')


def create_raw():
    header = {'type': 'double',
              'encoding': 'raw',
              }
    data = np.arange(5, dtype=float)
    nrrd.write('test-double-raw.nrrd', data, header)


def create_bz2():
    header = {'type': 'double',
              'encoding': 'bzip2',
              }
    data = np.arange(5, dtype=float)
    nrrd.write('test-double-bz2.nrrd', data, header)


def create_gzip():
    header = {'type': 'double',
              'encoding': 'gzip',
              }
    data = np.arange(5, dtype=float)
    nrrd.write('test-double-gzip.nrrd', data, header)


if __name__ == '__main__':
    create_header_test()
    create_raw()
    create_bz2()
    create_gzip()

